id: I92CB4189
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:25:43+00:00'
last_modified: '2022-06-09T04:51:44.551617+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14701
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་སྐྱོང་ཐུབ་པའི་འཕེལ་རྒྱས་འདུ་ཤེས་ཀྱི་ཡིག་ཆ་བདམས་བསྒྲིགས།（དགེ་རྒན་གྱི་ཁྲིད་དེབ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    D01A:
      image_group_id: I4PD4354
      title: Volume 1 of bod kyi srol rgyun skyong thub pa'i 'phel rgyas 'du shes
        kyi yig cha bdams bsgrigs/[（dge rgan gyi khrid deb/）
      total_pages: 358
      order: 1
      base_file: D01A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
