id: P007098
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14701
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་སྐྱོང་ཐུབ་པའི་འཕེལ་རྒྱས་འདུ་ཤེས་ཀྱི་ཡིག་ཆ་བདམས་བསྒྲིགས།（དགེ་རྒན་གྱི་ཁྲིད་དེབ།）
  author: ''
  volumes:
    52e1edf3aa0744bc844b7f7699726cea:
      image_group_id: I4PD4354
      title: ''
      volume_number: 1
      total_pages: 358
ebook_metadata:
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་སྐྱོང་ཐུབ་པའི་འཕེལ་རྒྱས་འདུ་ཤེས་ཀྱི་ཡིག་ཆ་བདམས་བསྒྲིགས།（དགེ་རྒན་གྱི་ཁྲིད་དེབ།）
  author: ''
  sku: P007098
  cover: cover.jpg
  layers:
  - pagination
