id: opecha:P007098
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14701
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་སྐྱོང་ཐུབ་པའི་འཕེལ་རྒྱས་འདུ་ཤེས་ཀྱི་ཡིག་ཆ་བདམས་བསྒྲིགས།（དགེ་རྒན་གྱི་ཁྲིད་དེབ།）
  volume:
    1a611498eab84ecc89acd97dca0fdc04:
      image_group_id: I4PD4354
      title: Volume 1 of bod kyi srol rgyun skyong thub pa'i 'phel rgyas 'du shes
        kyi yig cha bdams bsgrigs/[（dge rgan gyi khrid deb/）
      volume_number: 1
      total_pages: 358
  author: ''
ebook_metadata:
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་སྐྱོང་ཐུབ་པའི་འཕེལ་རྒྱས་འདུ་ཤེས་ཀྱི་ཡིག་ཆ་བདམས་བསྒྲིགས།（དགེ་རྒན་གྱི་ཁྲིད་དེབ།）
  author: ''
  sku: P007098
  cover: cover.jpg
  layers:
  - pagination
