id: P007098
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:41:31.196630
source_metadata:
  id: bdr:W1KG14701
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་སྐྱོང་ཐུབ་པའི་འཕེལ་རྒྱས་འདུ་ཤེས་ཀྱི་ཡིག་ཆ་བདམས་བསྒྲིགས།（དགེ་རྒན་གྱི་ཁྲིད་དེབ།）
  author: ''
  volumes:
    1a611498eab84ecc89acd97dca0fdc04:
      image_group_id: I4PD4354
      title: Volume 1 of bod kyi srol rgyun skyong thub pa'i 'phel rgyas 'du shes
        kyi yig cha bdams bsgrigs/[（dge rgan gyi khrid deb/）
      volume_number: 1
      total_pages: 358
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
